name = "bookmarkburst"
compatibility_date = "2025-04-09"
main = "workers-site/index.js"

# Configure for Cloudflare Pages deployment
[site]
bucket = "./dist"

# Specify the main file for Pages
main = "./client/dist/index.html" 